const {createClient}=supabase;const db=createClient(window.SUPABASE_CONFIG.url,window.SUPABASE_CONFIG.key);const $=id=>document.getElementById(id);const esc=s=>String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));let token="",staff="",sessionId="",items=[],current=null;
function setMsg(id,s){$(id).textContent=s||""}
async function login(){const name=$("staffName").value.trim(),pin=$("staffPin").value.trim();if(!name||!/^[0-9]{4,6}$/.test(pin))return setMsg("loginMsg","Enter staff name and 4–6 digit PIN.");$("loginBtn").disabled=true;try{const {data,error}=await db.rpc("inv_staff_login",{p_name:name,p_pin:pin});if(error)throw error;token=data.token;staff=data.staff_name;sessionStorage.setItem("inv_staff_token",token);sessionStorage.setItem("inv_staff_name",staff);$("login").classList.add("hidden");$("count").classList.remove("hidden");$("staffTitle").textContent=staff}catch(e){setMsg("loginMsg",e.message)}finally{$("loginBtn").disabled=false}}
async function start(){const section=$("section").value;const {data,error}=await db.rpc("inv_staff_start_session",{p_staff_token:token,p_section:section,p_date:new Date().toISOString().slice(0,10)});if(error)throw error;sessionId=data;const r=await db.rpc("inv_staff_get_items",{p_staff_token:token,p_section:section});if(r.error)throw r.error;items=r.data||[];renderList();$("counter").classList.remove("hidden");$("items").classList.remove("hidden");$("submitBtn").classList.remove("hidden");setMsg("sessionMsg",items.length+" items loaded.")}
function renderList(){const q=$("search").value.trim().toLowerCase();const filtered=items.filter(x=>!q||x.name.toLowerCase().includes(q)||String(x.barcode||"").includes(q));$("items").innerHTML=filtered.map(x=>'<button class="secondary itemPick" data-id="'+esc(x.id)+'" style="display:block;width:100%;margin:6px 0;text-align:left"><b>'+esc(x.name)+'</b><br><small>'+esc(x.category)+' · '+esc(x.base_uom)+' · count as '+esc(x.count_unit)+(Number(x.count_to_base)!==1?' · 1 '+esc(x.count_unit)+' = '+esc(x.count_to_base)+' '+esc(x.base_uom):'')+'</small></button>').join("")||'<div class="hint">No matching items.</div>';document.querySelectorAll(".itemPick").forEach(b=>b.onclick=()=>selectItem(b.dataset.id))}
function selectItem(id){current=items.find(x=>String(x.id)===String(id));if(!current)return;document.querySelectorAll(".itemPick").forEach(b=>b.classList.toggle("selected",String(b.dataset.id)===String(id)));$("countUnitLabel").textContent=current.count_unit||current.base_uom||"";$("itemInfo").innerHTML='<b>'+esc(current.name)+'</b><br>'+esc(current.category)+' · Base UOM: '+esc(current.base_uom)+' · Count as: '+esc(current.count_unit)+(Number(current.count_to_base)!==1?' · 1 '+esc(current.count_unit)+' = '+esc(current.count_to_base)+' '+esc(current.base_uom):'');$("countQty").value="";$("countQty").focus();updateConversion()}
async function scanBarcode(){if(!("BarcodeDetector" in window))return setMsg("savedMsg","Camera barcode scanning is not supported on this browser. Use the barcode input/search.");try{const d=new BarcodeDetector({formats:["ean_8","ean_13","upc_a","upc_e"]}),s=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"}}),v=document.createElement("video");v.srcObject=s;v.muted=true;v.playsInline=true;await v.play();const overlay=document.createElement("dialog");overlay.innerHTML='<p>Point camera at barcode…</p><button type="button">Cancel</button>';document.body.appendChild(overlay);overlay.querySelector("button").onclick=()=>{s.getTracks().forEach(t=>t.stop());overlay.remove()};overlay.showModal();const loop=async()=>{if(!document.body.contains(overlay))return;try{const z=await d.detect(v);if(z.length){const b=z[0].rawValue;overlay.close();s.getTracks().forEach(t=>t.stop());overlay.remove();$("search").value=b;renderList();const x=items.find(i=>String(i.barcode||"")===String(b));if(x)selectItem(x.id);return}}catch{}requestAnimationFrame(loop)};loop()}catch(e){setMsg("savedMsg","Could not start scanner: "+e.message)}}
function updateConversion(){if(!current)return;const n=Number($("countQty").value);$("conversion").textContent=Number.isFinite(n)&&n>=0?(n+" "+current.count_unit+" = "+(n*Number(current.count_to_base))+" "+current.base_uom):""}
async function save(){if(!current)return setMsg("savedMsg","Select an item.");const n=Number($("countQty").value);if(!Number.isFinite(n)||n<0)return setMsg("savedMsg","Enter a valid quantity.");$("saveBtn").disabled=true;try{const {data,error}=await db.rpc("inv_staff_save_count",{p_staff_token:token,p_session_id:sessionId,p_item_id:current.id,p_qty:n});if(error)throw error;setMsg("savedMsg","Saved: "+n+" "+data.count_unit+" = "+data.base_qty+" "+data.base_uom)}catch(e){setMsg("savedMsg",e.message)}finally{$("saveBtn").disabled=false}}
function next(){document.querySelectorAll(".itemPick").forEach(b=>b.classList.remove("selected"));$("countUnitLabel").textContent="";$("itemInfo").textContent="Select an item.";$("countQty").value="";$("conversion").textContent="";$("savedMsg").textContent="";current=null;$("search").focus()}
async function submit(){const {error}=await db.rpc("inv_staff_submit_session",{p_staff_token:token,p_session_id:sessionId});if(error)return setMsg("sessionMsg",error.message);setMsg("sessionMsg","Count submitted successfully.");$("submitBtn").disabled=true}
function logout(){sessionStorage.clear();location.reload()}
$("loginBtn").onclick=login;$("startBtn").onclick=()=>start().catch(e=>setMsg("sessionMsg",e.message));$("saveBtn").onclick=save;$("nextBtn").onclick=next;$("submitBtn").onclick=submit;$("logoutBtn").onclick=logout;$("search").oninput=renderList;$("scanBtn").onclick=scanBarcode;$("countQty").oninput=updateConversion;$("staffPin").onkeydown=e=>{if(e.key==="Enter")login()};token=sessionStorage.getItem("inv_staff_token")||"";staff=sessionStorage.getItem("inv_staff_name")||"";if(token){$("login").classList.add("hidden");$("count").classList.remove("hidden");$("staffTitle").textContent=staff}