(()=>{"use strict";
const db=window.supabase.createClient(window.SUPABASE_CONFIG.url,window.SUPABASE_CONFIG.key);
const $=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
const state={type:"warehouse_staff",rows:[],editId:null};
function ensureForm(){if($("teamMemberDialog"))return;const d=document.createElement("dialog");d.id="teamMemberDialog";d.className="settingsDialog";d.innerHTML='<form method="dialog" id="teamMemberForm"><div class="settingsDialogHead"><div><span class="eyebrow">TEAM CREDENTIALS</span><h3 id="teamMemberTitle">Add Team Member</h3><p class="hint">PIN/password values are never displayed after saving.</p></div><button value="cancel" class="secondary">✕</button></div><label>Name*<input id="teamMemberName" required autocomplete="off"></label><label id="teamLoginWrap">Login name*<input id="teamMemberLogin" autocomplete="off"></label><label>PIN* for new member / leave blank to keep existing<input id="teamMemberPin" type="password" inputmode="numeric" maxlength="6" autocomplete="new-password"></label><label id="teamPaymentWrap">Payment confirmation password (optional)<input id="teamMemberPayment" type="password" autocomplete="new-password"></label><p id="teamMemberError" class="adminAuthError"></p><menu><button value="cancel" class="secondary">Cancel</button><button id="teamMemberSave" value="default" class="primary">Save</button></menu></form></dialog>';document.body.appendChild(d);$("teamMemberForm").addEventListener("submit",save)}
async function load(){const box=$("teamList");if(!box)return;box.innerHTML='<div class="hint">Loading team…</div>';const{data,error}=await db.rpc("inv_admin_get_team",{p_admin_token:window.PA_ADMIN_SESSION});if(error){box.innerHTML='<div class="hint">Could not load team: '+esc(error.message)+'</div>';return}state.rows=data||[];render();loadAudit()}
function render(){const rows=state.rows.filter(x=>x.member_type===state.type);$("teamList").innerHTML=rows.length?rows.map(x=>'<div class="teamRow"><div><b>'+esc(x.name)+'</b><span>'+(x.member_type==="driver"?esc(x.login_name||"No login"):"Warehouse inventory access")+'</span></div><div class="teamRowActions"><span class="statusPill '+(x.active?"on":"off")+'">'+(x.active?"Active":"Inactive")+'</span><button class="secondary teamEdit" data-id="'+x.member_id+'">Edit</button><button class="'+(x.active?"dangerBtn":"secondary")+' teamToggle" data-id="'+x.member_id+'">'+(x.active?"Deactivate":"Activate")+'</button></div></div>').join(""):'<div class="hint">No team members yet.</div>';document.querySelectorAll(".teamEdit").forEach(b=>b.onclick=()=>open(b.dataset.id));document.querySelectorAll(".teamToggle").forEach(b=>b.onclick=()=>toggle(b.dataset.id))}
async function loadAudit(){const{data,error}=await db.rpc("inv_admin_get_team_audit",{p_admin_token:window.PA_ADMIN_SESSION});if(error){$("teamAuditList").innerHTML='<div class="hint">Could not load audit log.</div>';return}$("teamAuditList").innerHTML=(data||[]).slice(0,30).map(x=>'<div class="teamAuditRow"><b>'+esc(x.action)+'</b><span>'+esc(x.member_type.replace("_"," "))+' · '+new Date(x.created_at).toLocaleString("en-IN")+'</span></div>').join("")||'<div class="hint">No credential changes recorded.</div>'}
function open(id=null){ensureForm();state.editId=id;const x=id?state.rows.find(i=>i.member_id===id):null;$("teamMemberTitle").textContent=id?"Edit Team Member":"Add Team Member";$("teamMemberName").value=x?.name||"";$("teamMemberLogin").value=x?.login_name||"";$("teamMemberPin").value="";$("teamMemberPayment").value="";$("teamMemberError").textContent="";$("teamLoginWrap").classList.toggle("hidden",state.type!=="driver");$("teamPaymentWrap").classList.toggle("hidden",state.type!=="driver");$("teamMemberPin").required=!id;$("teamMemberDialog").showModal();$("teamMemberName").focus()}
async function save(e){e.preventDefault();const name=$("teamMemberName").value.trim(),login=$("teamMemberLogin").value.trim(),pin=$("teamMemberPin").value.trim(),payment=$("teamMemberPayment").value;if(!name)return $("teamMemberError").textContent="Name is required.";if(state.type==="driver"&&!login)return $("teamMemberError").textContent="Login name is required.";if(pin&&!/^\d{4,6}$/.test(pin))return $("teamMemberError").textContent="PIN must be 4–6 digits.";const b=$("teamMemberSave");b.disabled=true;b.textContent="Saving…";try{const{error}=await db.rpc("inv_admin_save_team_member",{p_admin_token:window.PA_ADMIN_SESSION,p_member_type:state.type,p_member_id:state.editId||null,p_name:name,p_login_name:state.type==="driver"?login:null,p_pin:pin||null,p_payment_password:state.type==="driver"?(payment||null):null});if(error)throw error;$("teamMemberDialog").close();await load();}catch(x){$("teamMemberError").textContent=x.message||"Could not save team member."}finally{b.disabled=false;b.textContent="Save"}}
async function toggle(id){const x=state.rows.find(i=>i.member_id===id);if(!x)return;const active=!x.active;if(!active&&!confirm("Deactivate "+x.name+"? Existing historical records will remain."))return;try{const{error}=await db.rpc("inv_admin_set_team_active",{p_admin_token:window.PA_ADMIN_SESSION,p_member_type:x.member_type,p_member_id:id,p_active:active});if(error)throw error;await load()}catch(e){alert("Could not change team member: "+e.message)}}
function show(){if(!window.PA_ADMIN_SESSION)return window.PA_REAUTH_ADMIN?.();$("manageTeamDialog").showModal();load()}
function init(){document.getElementById("menuManageTeam")?.addEventListener("click",()=>{document.getElementById("adminMenu")?.classList.add("hidden");show()});document.getElementById("closeManageTeam")?.addEventListener("click",()=>$("manageTeamDialog")?.close());document.getElementById("manageTeamDashboardBack")?.addEventListener("click",()=>{$("manageTeamDialog")?.close();window.showAdminDashboard?.()});document.getElementById("addTeamMember")?.addEventListener("click",()=>open());document.getElementById("refreshTeam")?.addEventListener("click",load);document.querySelectorAll(".teamTab").forEach(b=>b.addEventListener("click",()=>{state.type=b.dataset.teamType;document.querySelectorAll(".teamTab").forEach(x=>x.classList.toggle("active",x===b));$("addTeamMember").textContent=state.type==="driver"?"+ Add Driver":"+ Add Staff";render()}))}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();