const DRIVER_API=window.SUPABASE_CONFIG.url+"/functions/v1/driver-api";const DRIVER_KEY=window.SUPABASE_CONFIG.key;const ds={token:localStorage.getItem("pa_driver_session")||"",name:localStorage.getItem("pa_driver_name")||"",orderId:null,outlets:[],earned:0};const $=id=>document.getElementById(id);function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));}async function api(action,body={}){const r=await fetch(DRIVER_API,{method:"POST",headers:{"apikey":DRIVER_KEY,"Content-Type":"application/json","x-driver-session":ds.token},body:JSON.stringify({action,session_token:ds.token,...body})});const d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.message||"Request failed");return d;}function render(){
  $("driverLogin").classList.toggle("hidden",!!ds.token);
  $("driverHome").classList.toggle("hidden",!ds.token);
  $("driverLogout").classList.toggle("hidden",!ds.token);
  $("driverName").textContent=ds.name||"Driver";

  const earned=Number(ds.earned||0);
  $("driverEarnings").innerHTML=
    '<div class="driverEarnCard"><div><span class="eyebrow">DELIVERY EARNINGS</span><h3>₹'+earned.toFixed(2)+'</h3><p>Earned from completed deliveries</p></div><div class="earnIcon">₹</div></div>';

  const box=$("driverOutletCards");
  box.innerHTML=ds.outlets.map(o=>{
    const d=o.delivery||{},delivered=d.status==="delivered",packed=o.status==="completed";
    const items=o.items||[];
    const exceptions=items.filter(i=>i.status==="MISSING"||i.status==="PARTIAL");
    const required=items.reduce((s,i)=>s+Number(i.required_qty||0),0);
    const missing=items.reduce((s,i)=>s+Number(i.missing_qty||0),0);
    const mapUrl="https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(o.outlet_name+" Ahmedabad Gujarat");
    const itemRows=items.map(i=>'<tr><td><b>'+esc(i.product_name)+'</b><small>'+esc(i.item_code||"")+'</small></td><td>'+Number(i.required_qty||0)+'</td><td>'+Number(i.packed_qty||0)+'</td><td>'+Number(i.missing_qty||0)+'</td><td><span class="itemStatus '+String(i.status||"PENDING").toLowerCase()+'">'+esc(i.status||"PENDING")+'</span>'+(i.reason?'<small>'+esc(i.reason)+'</small>':"")+'</td></tr>').join("");
    return '<article class="driverOutletCard">'+
      '<div class="driverOutletTop"><div><span class="eyebrow">RANK '+o.rank+'</span><h3>'+esc(o.outlet_name)+'</h3></div><span class="miniStatus '+(delivered?"completed":packed?"packed":"pending")+'">'+(delivered?"DELIVERED":packed?"READY FOR DELIVERY":"WAITING FOR PACKING")+'</span></div>'+
      '<div class="driverOutletStats"><span><b>'+items.length+'</b> Items</span><span><b>'+required+'</b> Required</span><span><b>'+missing+'</b> Missing</span><span><b>₹'+Number(d.earned||0).toFixed(0)+'</b> Earned</span></div>'+
      '<div class="driverDeliveryMeta"><span>Invoice: '+(d.invoice_path?"Uploaded":"Not uploaded")+'</span><span>'+ (d.delivered_at?new Date(d.delivered_at).toLocaleString("en-IN"):"")+'</span></div>'+
      '<div class="driverActions"><a class="secondary mapBtn" target="_blank" rel="noopener" href="'+mapUrl+'">📍 Google Maps</a>'+
      (packed&&!delivered?'<button class="secondary invoiceBtn" data-id="'+o.outlet_id+'">📷 Upload Invoice</button><button class="primary deliverBtn" data-id="'+o.outlet_id+'" '+(!d.invoice_path?"disabled":"")+'>✓ Mark Delivered</button>':delivered?'<span class="deliveredNote">✓ Delivery completed • ₹'+Number(d.earned||0).toFixed(2)+'</span>':"")+
      '</div>'+
      '<details class="driverItems"><summary>View item-wise packing'+(exceptions.length?' • '+exceptions.length+' Missing/Partial':"")+'</summary><div class="tableWrap"><table><thead><tr><th>Item</th><th>Req.</th><th>Packed</th><th>Missing</th><th>Status</th></tr></thead><tbody>'+itemRows+'</tbody></table></div></details>'+
    '</article>';
  }).join("")||'<div class="hint">No outlets assigned in the current order.</div>';

  box.querySelectorAll(".invoiceBtn").forEach(b=>b.onclick=()=>chooseInvoice(b.dataset.id));
  box.querySelectorAll(".deliverBtn").forEach(b=>b.onclick=()=>markDelivered(b.dataset.id));
}async function refresh(){try{const d=await api("dashboard");ds.name=d.driver_name;ds.orderId=d.order_id;ds.outlets=d.outlets||[];ds.earned=Number(d.earned||0);localStorage.setItem("pa_driver_name",ds.name);render();}catch(e){if(/session expired/i.test(e.message)){logout();return}alert(e.message);}}async function login(){const name=$("driverLoginName").value.trim(),pin=$("driverPin").value.trim();if(!name||!pin)return;$("driverLoginMsg").textContent="Signing in…";try{const d=await fetch(DRIVER_API,{method:"POST",headers:{"apikey":DRIVER_KEY,"Content-Type":"application/json"},body:JSON.stringify({action:"login",login_name:name,pin})}).then(async r=>{const x=await r.json();if(!r.ok||x.ok===false)throw new Error(x.message||"Login failed");return x;});ds.token=d.token;ds.name=d.driver_name;localStorage.setItem("pa_driver_session",ds.token);localStorage.setItem("pa_driver_name",ds.name);await refresh();}catch(e){$("driverLoginMsg").textContent=e.message;}}function logout(){ds.token="";ds.name="";ds.orderId=null;ds.outlets=[];ds.earned=0;localStorage.removeItem("pa_driver_session");localStorage.removeItem("pa_driver_name");render();}async function chooseInvoice(outletId){$("invoiceInput").value="";$("invoiceInput").dataset.outletId=outletId;$("invoiceInput").click();}$("invoiceInput").onchange=async e=>{const file=e.target.files[0],outletId=e.target.dataset.outletId;if(!file||!outletId)return;if(!file.type.startsWith("image/"))return alert("Please select an invoice image.");if(file.size>10*1024*1024)return alert("Invoice image must be under 10 MB.");try{const d=await api("upload_url",{order_id:ds.orderId,outlet_id:outletId,filename:file.name,mime_type:file.type,extension:(file.name.split(".").pop()||"jpg")});const {error}=await supabase.storage.from("delivery-invoices").uploadToSignedUrl(d.path,d.token,file);if(error)throw error;alert("Invoice uploaded. Now tap Mark Delivered.");await refresh();}catch(err){alert("Invoice upload failed: "+err.message);}};async function markDelivered(outletId){if(!confirm("Mark this outlet as delivered?"))return;try{await api("mark_delivered",{order_id:ds.orderId,outlet_id:outletId});await refresh();}catch(e){alert(e.message);}}$("driverLoginBtn").onclick=login;$("driverPin").onkeydown=e=>{if(e.key==="Enter")login()};$("driverLogout").onclick=logout;$("driverRefresh").onclick=refresh;if(ds.token)refresh();else render();